config/routes.rb
EdAlbum::Application.routes.draw do
match 'exit' => 'home#logout', :as => :logout
match 'delete_album/:id' => 'albums#destroy', :as => :delete_album
match '/albums/:album_id/photos/:photo_id/comments' => 'comments#create', :as => :new_comment
match '/albums/:album_id/delete_photos/:id' => 'photos#destroy', :as => :delete_photo
match '/delete_users/:id' => 'users#destroy', :as=> :delete_user
  resources :albums do
    resources :photos do
      resources :comments
    collection do
      get 'all_album_photos'
    end
    member do
      get  'download'
      get 'set_cover_photo'
    end
    end
   collection do
     get 'my_albums'
     get 'add_photo'
     get 'all_albums'
   end
  end
	
	resources :likes do
	collection do
  get 'photo_like'
	get 'photo_unlike'	
  end
	member do
	get 'album_like'
	get 'album_unlike'
  get 'all_album_like'
	get 'all_album_unlike'
	get 'comment_like'
	get 'comment_unlike'
  get 'solution_like'
  get 'solution_unlike'
	end
	end
  resources :users do
    collection do
     post 'modify_password'
     get 'admin'
     get 'employee'
     get 'change_password'
   end
  end

  resources :home do
    collection do 
      post 'check_login'
      delete 'logout'
      get 'login'
      get 'home_page'
    end
  end

  resources :emailer do
    collection do
     get 'mail'
     get 'new_email' 
     post 'sendmail'
     get 'admin'
     post 'employee_email'
   end
  end
 

  resources :problems do
     get 'new'
  end

	resources :solutions do
     collection do
     	get 'search_solutions'
     	get 'create_solution'
     	post 'solutions' 
     	get 'search'
     end
     member do
     get 'verify'
     get 'reject'
     end
  end
	
	resources :suggestions do
		collection do
    	 get 'event'
    	 get 'create_event'
     end
  end
  


  root :to => 'home#home_page'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  cattr_reader :page
  @@page = 5

  has_many :albums, :dependent => :destroy
  has_many :comments, :dependent => :destroy 
  has_many :photos, :through => :comments 
  has_many :likes, :as => :likedto , :dependent => :destroy
	has_many :problems, :dependent => :destroy

  has_many :solutions, :dependent => :destroy  
	has_attached_file :user_image, :styles => { :medium => "300x300>", :thumb => "100x100>", :profile => "150x150>", :comment_pic => "80x80>" }, :default_url => '/images/user_d.jpeg'
  
  validates :login_name, :presence => { :message => " is required" }

  validates :login_name, :length => {
    :minimum   => 5,
    :maximum   => 30,
    :too_short => "must have at least %{count} char",
    :too_long  => "must have at most %{count} char"
  }
  validates :login_password, :presence => { :message => " is required" }

	validates :login_password, :confirmation => true
  validates :login_password_confirmation, :presence => true 
  validates :first_name, :presence => { :message => " is required" }
  validates :last_name, :presence => { :message => " is required" }  
  validates_presence_of :date_of_birth, :unless => Proc.new { |user| user.date_of_birth <= Time.now}, :messgae=>" is reqired"

  validates :login_role, :presence => { :message => " is required" }
  validates :email_id, :presence => { :message => " is required" }
validates :email_id,:format => { :with => /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]+$/,:message => " is invalid " }


  validates :login_name, :uniqueness => { :message => " is already register" }
  validates :email_id, :uniqueness => { :message => " is already register" }

  def name
    first_name + ' ' + last_name
  end 

  def self.admin?(user)
    user.login_role.to_s.downcase == 'admin'
  end

  def self.home_url(user)
    return "/home/home_page" if user.blank?
    case user.login_role.to_s.downcase
      when "admin"
        "/users/admin"
      when "employee"
        "/users/employee"
      end
    end
end

app/controllers/users_controller.rb
require 'digest/sha2'
require 'will_paginate'
class UsersController < ApplicationController
  before_filter :require_user
  layout :set_layout 
  # GET /users
  # GET /users.json
#   layout 'admin_layout' , :except => [:employee , :change_password]
  def admin
    @suggestion = Suggestion.where('ed_date >= ?',Time.now.strftime("%Y-%m-%d")).paginate(:page => params[:page], :per_page => 5)
       
  end

  def employee
    @suggestion = Suggestion.where('ed_date >= ?',Time.now.strftime("%Y-%m-%d")).paginate(:page => params[:page], :per_page => 5)
  end

  def change_password
    
  end

  def index
		set_default_flash       
    @users = User.all.paginate(:page => params[:page], :per_page => 10)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json=> @users }
      end   
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user = User.find(params[:id])
       respond_to do |format|
       format.html # show.html.erb
       format.json { render json=> @user }     
       end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if current_user.login_role.to_s.downcase == 'admin'
      @user = User.new
        respond_to do |format|
        format.html # new.html.erb
        format.json { render json=> @user }
       end
    else
      flash[:error]="authentication fail !" 
      redirect_to logout_home_index_path
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
      respond_to do |format|
      @user.login_password = get_encryp_pass(@user.login_password)
			@user.login_password_confirmation = get_encryp_pass(@user.login_password_confirmation)
       if @user.save
        flash[:notice]="User successfully created !" 
        format.html { redirect_to :controller =>'users',:action => 'admin'}
        else
          flash[:error]="Please fill all required fields !"
         @user.login_password = nil
				 @user.login_password_confirmation = nil
         format.html { render :action=> "new" }
       end
    end
  end
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      params[:user][:login_password] = get_encryp_pass(params[:user][:login_password])
			params[:user][:login_password_confirmation] = get_encryp_pass(params[:user][:login_password_confirmation])
      if @user.update_attributes(params[:user])
        flash[:notice]='User detail successfully updated.'
        format.html { redirect_to @user}
      else
        format.html { render :action=> "edit" }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user.login_role.to_s.downcase == 'admin'
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice]="User successfully deleted ! "
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
    else
       redirect_to logout_home_index_path
    end
  end
 
  def modify_password
    current_password = get_encryp_pass(params[:current_password])
    new_password = get_encryp_pass(params[:new_password])
    @user = User.find(:first, :conditions=>[" login_password = ? and id = ? ", current_password, current_user.id])
      if @user then
        @user.login_password = new_password
        @user.save
        flash[:notice]="Password successfully changed ! "
        if current_user.login_role.to_s.downcase == 'admin'
           redirect_to :action => 'admin'
        else
           redirect_to :action => 'employee'
        end
      else 
        flash[:error] = "You have entered wrong current password. Please try again !"
        redirect_to :action => 'change_password'
      end
   end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div style="text-align:center">
<%= form_for(@user, :html => {:id => 'user', :name => 'user_form', :onsubmit => "return validate_email();"}) do |f| %>  
  <center>
    <table>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :login_ID %></b></td><td><%= f.text_field :login_name %></td>
          <%unless @user.errors[:login_name].blank?%> <td class="validation_error">Login Id<%=@user.errors[:login_name]%></td>  <%end%>
        </div>
      </tr>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :login_password %></b></td><td><%= f.password_field :login_password %></td>
           <%unless @user.errors[:login_password].blank?%> <td class="validation_error">Login Password <%=@user.errors[:login_password]%></td>  <%end%>
         </div>
      </tr>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :confirm_password %></td><td><%= f.password_field :login_password_confirmation %></td>
           <%unless @user.errors[:login_password_confirmation].blank?%> <td class="validation_error">Confirm Password <%=@user.errors[:login_password_confirmation].blank?%></td>  <%end%>
         </div>
      </tr>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :first_name %></b></td></td><td><%= f.text_field :first_name %></td>
           <%unless @user.errors[:first_name].blank?%> <td class="validation_error">First Name<%=@user.errors[:first_name]%></td>  <%end%>
         </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :last_name %></b></td><td><%= f.text_field :last_name %></td>
           <%unless @user.errors[:last_name].blank?%> <td class="validation_error">Last Name<%=@user.errors[:last_name]%></td>  <%end%>
        </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :login_role %></b></td><td><%= f.select :login_role, options_for_select([["Select One", ""], "Admin", "Employee"])%>
           <%unless @user.errors[:login_role].blank?%> <td class="validation_error">Login Role<%=@user.errors[:login_role]%></td>  <%end%>
        </div>
        </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :email_id %></b></td><td><%= f.text_field :email_id, :id =>'mail' %></td>
           <%unless @user.errors[:email_id].blank?%> <td class="validation_error">Email-ID<%=@user.errors[:email_id]%></td>  <%end%>
        </div>
      </tr>
      
      <tr>
        <div class="actions">
<td></td>      
    <td><b><%= f.submit %></b></td><td></td>
        </div>
      </tr>
  </table>
 </center>
<% end %>
</div>

app/views/users/_user_fields.html.erb
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :login_name, 'Login	ID' %></b></td><td><%= f.text_field :login_name, :placeholder => 'Enter Login ID...' %></td>
          <%unless @user.errors[:login_name].blank?%> <td class="validation_error">Login Id <%=@user.errors[:login_name].first%></td>  <%end%>
        </div>
      </tr>
		<% unless show_image==true %>      
			<tr>
         <div class="field">
           <td align="right"><b><%= f.label :password %></b></td><td><%= f.password_field :login_password %></td>
           <%unless @user.errors[:login_password].blank?%> <td class="validation_error">Login Password <%=@user.errors[:login_password].first%></td>  <%end%>
         </div>
      </tr>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :password_confirmation %></td><td><%= f.password_field :login_password_confirmation %></td>
           <%unless @user.errors[:login_password_confirmation].blank?%> <td class="validation_error">Confirm Password <%=@user.errors[:login_password_confirmation].first?%></td>  <%end%>
         </div>
      </tr>
			<% end %>
      <tr>
         <div class="field">
           <td align="right"><b><%= f.label :first_name, 'First Name' %></b></td></td><td><%= f.text_field :first_name, :placeholder => 'Enter First Name...' %></td>
           <%unless @user.errors[:first_name].blank?%> <td class="validation_error">First Name<%=@user.errors[:first_name].first%></td>  <%end%>
         </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :last_name %></b></td><td><%= f.text_field :last_name, :placeholder => 'Enter Last Name...' %></td>
           <%unless @user.errors[:last_name].blank?%> <td class="validation_error">Last Name<%=@user.errors[:last_name].first%></td>  <%end%>
        </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :login_role %></b></td><td><%= f.select :login_role, [['Admin','Admin'],  ['Employee','Employee']] %>
           <%unless @user.errors[:login_role].blank?%> <td class="validation_error">Login Role<%=@user.errors[:login_role].first%></td>  <%end%>
        </div>
        </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :email_id %></b></td><td><%= f.text_field :email_id, :id =>'mail', :placeholder => 'Enter Email-ID...' %></td> 
           <%unless @user.errors[:email_id].blank?%> <td class="validation_error">Email-ID<%=@user.errors[:email_id].first%></td>  <%end%>
        </div>
      </tr>
<% unless show_image==true %>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :user_image %></b></td><td><%= f.file_field :user_image %></td>           
        </div>
      </tr>
<% end %>

      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :mobile_no %></b></td><td><%= f.text_field :mobile_no, :placeholder => 'Enter Mobile No...' %></td>
           <%unless @user.errors[:mobile_no].blank?%> <td class="validation_error">Mobile No.<%=@user.errors[:mobile_no].first%></td>  <%end%>
        </div>
      </tr>

      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :phone_no %></b></td><td><%= f.text_field :phone_no, :placeholder => 'Enter Phone No...' %></td>
           <%unless @user.errors[:phone_no].blank?%> <td class="validation_error">Phone No.<%=@user.errors[:phone_no].first%></td>  <%end%>
        </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :local_address %></b></td><td><%= f.text_field :local_address, :placeholder => 'Enter Local Address...' %></td>
           <%unless @user.errors[:local_address].blank?%> <td class="validation_error">Local Address.<%=@user.errors[:local_address].first%></td>  <%end%>
        </div>
      </tr>
      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :permanent_address %></b></td><td><%= f.text_field :permanent_address, :placeholder => 'Enter Permanent Address...' %></td>
           <%unless @user.errors[:permanent_address].blank?%> <td class="validation_error">Permanent Address.<%=@user.errors[:permanent_address].first%></td>  <%end%>
        </div>
      </tr>

      <tr>
        <div class="field">
           <td align="right"><b><%= f.label :date_of_birth %></b></td><td><%= f.date_select("date_of_birth", :order => [:day, :month, :year], :start_year => 1920) %></td>
           <%unless @user.errors[:date_of_birth].blank?%> <td class="validation_error">Date of Birth.<%=@user.errors[:date_of_birth]%></td>  <%end%><%unless @user.errors[:date_of_birth].blank?%> <td class="validation_error">Login Role<%=@user.errors[:date_of_birth].first%></td>  <%end%>
        </div>
      </tr>

app/views/users/admin.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message =>''} %>
<%= render :partial => 'suggestions/event'%>

app/views/users/change_password.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message =>'CHANGE PASSWORD'} %>

<form method="post" action="/users/modify_password" name="change_password_form" onsubmit="return validateForm()">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>" />
  <center>
    <table>
       <tr>
	 <TD align="right"><b>Enter current password</b></TD><Td><input type="password" name="current_password" size="20"></Td>
       </tr>
       <tr>
 	 <TD align="right"><b>Enter new password</b></TD><Td><input type="password" name="new_password" size="20"></Td>
       </tr>
       <tr>
	  <TD align="right"><b>Enter new password again</b></TD><Td><input type="password" name="con_password" size="20"></Td>
       </tr>
       <tr>
      <td></td>
	  <td colspan="2"><input type="submit" name="submit" value="CHANGE PASSWORD"></td>
       </tr>
      </table>
    </center>
</form>

app/views/users/edit.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message =>'UPDATE EMPLOYEE INFORMATION'} %>
<%= render 'form' %>
 <%= link_to 'Show', @user %>
  <%= link_to 'Back', users_path %>

app/views/users/employee.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message =>'EMPLOYEE HOME PAGE'} %>
<%= render :partial => 'suggestions/event'%>

app/views/users/index.html.erb
<% content_for :header do %>
  <style type="text/css">
    .center_align, th	{
      text-align:center;
    }
  </style>
<% end %>

<%= render :partial =>'home/marquee',:locals=>{:message =>'EMPLOYEE INFORMATION'} %>
<% row_count=0 %>
<% colspan_count = User.admin?(current_user) ? 8 : 6 %>
<center>
 <table>
  <tr>
    <th >Seq No</th>
    <th>Login name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Login role</th>
    <th>Email</th>
    <th></th>
    <% if User.admin?(current_user) %>
    <th></th>
    <th></th>
    <% end %>
  </tr>

   <% @users.each do |user| %>  
   <tr>
    <td class="center_align"><%= row_count+=1 %> </td>
     <td><b><%= user.login_name.titleize %></b></td>
     <td><b><%= user.first_name.titleize %></b></td>
     <td><b><%= user.last_name.titleize %></b></td>
     <td><b><%= user.login_role.titleize %></b></td>
     <td><b><%= user.email_id %></b></td>
     <td><%= link_to 'Show', user %></td>
    <% if User.admin?(current_user) %>
     <td> <%= link_to 'Edit', edit_user_path(user) %> </td>
     <td> <%= link_to 'Destroy',delete_user_path(user), :confirm => 'Are you sure?' %></td>
    <% end %>


   </tr>
  <% end %>
 </table>
<script>$("tr:odd").css("background-color", "#EBECE4");</script>
</center>
<br/>
<%= will_paginate @users %>
<%= link_to 'Back', :controller =>'users',:action => 'admin' %>

app/views/users/new.html.erb
<div class="clear"></div>
<%= render :partial =>'home/marquee',:locals=>{:message =>'ADD NEW EMPLOYEE'} %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message =>'EMPLOYEE INFORMATION'} %>
<center>
   <table border="2">
     <tr>
         <td><b>Login name:</b></td><td><%= @user.login_name %></td>
     </tr>
     <tr>
         <td><b>Login password:</b></td><td><%= @user.login_password %></td>
     </tr>
     <tr>
         <td><b>First name:</b></td><td><%= @user.first_name %></td>
     </tr>
     <tr>
         <td><b>Last name:</b></td><td><%= @user.last_name %></td>
     </tr>
         <td><b>Login role:</b></td><td><%= @user.login_role %></td>
     </tr>
     <tr>
        <td><b>Email:</b></td><td><%= @user.email_id %></td>
    </table>
</center>
<br><br><br><br>
<%= link_to 'Back', users_path %>