config/routes.rb
EdAlbum::Application.routes.draw do
match 'exit' => 'home#logout', :as => :logout
match 'delete_album/:id' => 'albums#destroy', :as => :delete_album
match '/albums/:album_id/photos/:photo_id/comments' => 'comments#create', :as => :new_comment
match '/albums/:album_id/delete_photos/:id' => 'photos#destroy', :as => :delete_photo
match '/delete_users/:id' => 'users#destroy', :as=> :delete_user
  resources :albums do
    resources :photos do
      resources :comments
    collection do
      get 'all_album_photos'
    end
    member do
      get  'download'
      get 'set_cover_photo'
    end
    end
   collection do
     get 'my_albums'
     get 'add_photo'
     get 'all_albums'
   end
  end
	
	resources :likes do
	collection do
  get 'photo_like'
	get 'photo_unlike'	
  end
	member do
	get 'album_like'
	get 'album_unlike'
  get 'all_album_like'
	get 'all_album_unlike'
	get 'comment_like'
	get 'comment_unlike'
  get 'solution_like'
  get 'solution_unlike'
	end
	end
  resources :users do
    collection do
     post 'modify_password'
     get 'admin'
     get 'employee'
     get 'change_password'
   end
  end

  resources :home do
    collection do 
      post 'check_login'
      delete 'logout'
      get 'login'
      get 'home_page'
    end
  end

  resources :emailer do
    collection do
     get 'mail'
     get 'new_email' 
     post 'sendmail'
     get 'admin'
     post 'employee_email'
   end
  end
 

  resources :problems do
     get 'new'
  end

	resources :solutions do
     collection do
     	get 'search_solutions'
     	get 'create_solution'
     	post 'solutions' 
     	get 'search'
     end
     member do
     get 'verify'
     get 'reject'
     end
  end
	
	resources :suggestions do
		collection do
    	 get 'event'
    	 get 'create_event'
     end
  end
  


  root :to => 'home#home_page'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/album.rb
class Album < ActiveRecord::Base  
	has_many :likes, :as => :likedto, :dependent => :destroy
  #after_create :send_mail
  belongs_to :user
  has_many :photos ,:dependent => :destroy
  belongs_to :cover_photo, :class_name => "Photo" ,:foreign_key =>'cover_photo_id'
  accepts_nested_attributes_for :photos, :allow_destroy  => true

  validates :album_name, :presence => { :message => " is required" }
  validates :album_description, :presence => { :message => " is required" }

  def is_owner?(user)
    album =  user.albums.find(:first,:conditions=>[" id = ? " , self.id]) 
    album ? true : false 
  end

  def name
    first_name + ' ' + last_name
  end
end


=begin
  def send_mail
    recipients = User.all
    recipients.each do |user|
      if user.name != self.user.name
        Emailer.new_album_email(user, self).deliver
      end
    end
    self.save
  end
=end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :require_user
  layout :set_layout
  

  # GET /albums
  def index
    #@albums = Album.all
    @albums = Album.all.paginate(:page=>params[:page],:per_page=>9)
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json=> @albums }
      end
  end

  # GET /albums/1
  def show
    @album = Album.find(params[:id])
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json=> @album }
    end
  end

  # GET /albums/new
  def new
    @album = Album.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json=> @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = current_user.albums.find(params[:id])
  end

  # POST /albums
  def create
    @album = current_user.albums.build(params[:album])    
    respond_to do |format|
      if @album.save
        flash[:notice]="Album successfully created !"
        format.html { redirect_to @album}
      else
        format.html { render :action=> "new" }
      end
    end
  end

  # PUT /albums/1
  def update
    @album = current_user.albums.find(params[:id])
    if @album 
	respond_to do |format|
	  if @album.update_attributes(params[:album])
	    format.html { redirect_to @album, notice=> 'Album was successfully updated.' }
	  else
	    format.html { render action=> "edit" }
	  end
	end
    else

    end
  end

  # DELETE /albums/1
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:notice]="Album Deleted Successfully"
    respond_to do |format|
      format.html { redirect_to my_albums_albums_url }
    end
  end

  def my_albums
    @albums = Album.find(:all,:conditions=>[" user_id = ? " , current_user.id] )
    @albums = Album.find(:all,:conditions=>[" user_id = ? " , current_user.id]).paginate(:page=>params[:page],:per_page=>9)    
    render :template => 'albums/index'
  end

  def all_albums
    #@albums = Album.find(:all,:conditions=>[" user_id = ? " , current_user.id] )
    #@albums = current_user.albums
    @albums = Album.all.paginate(:page=>params[:page],:per_page=>9)
    render :template => 'albums/all_albums'
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper

end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <br><br>
  <center>
    <table>
     <tr>
        <div class="field">
       <td align="right"><b><%= f.label :album_name %></b></td><td><%= f.text_field :album_name %></td>
<%unless @album.errors[:album_name].blank?%> <td class="validation_error_new_album">Album Name <%=@album.errors[:album_name]%></td>  <%end%>
      </div>
     </tr>
     <tr> 
      <div class="field">
        <td align="right"> <b><%= f.label :album_description %></b></td><td><%= f.text_field :album_description %></td><%unless @album.errors[:album_description].blank?%> <td class="validation_error_new_album">Album Description <%=@album.errors[:album_description]%></td>  <%end%>
      </div>
      </tr>
      <tr>
      <div class="actions">
         <td></td><td><%= f.submit %></td>
      </div>
      </tr>
    </table>
   </center>
<% end %>
<br><br><br>

app/views/albums/all_albums.html.erb
<center>
<div class="row">
  <div class="clear"></div>
<%= render :partial =>'home/marquee',:locals=>{:message =>"All Albums"} %> 
  <% count=0 %>
  <table >
  <% @albums.each do |album| %>
      <% if count%3==0 %>
        <tr>
      <% end %>
<td>

<table align="center">
<tr>
<td>
  
      <td align="center">
        <div class="col1">
          <div class="album_info">
            <font color="blue">Album Name : <%= album.album_name.titleize %></font>
          </div>
          <% if album.cover_photo %>
            <%= link_to image_tag( album.cover_photo.image.url(:original) , :height => "200" , :width => "200" , :title => "Show photos") , album_photos_path(album)  %>
          <% else %>
            <%= link_to image_tag( '/images/admin.jpeg' , :height => "200" , :width => "200" , :title => "Show photos") , album_photos_path(album)  %>
          <% end %>
          
          <div class="link">
            <font color="blue"> By <%= album.user.name.titleize %></font>
          </div> 
          <div class="album_link" style="margin-left:10px;">
    <%= ( link_to image_tag("/images/delete_img.jpeg" ,:height => "20" , :width => "20" , :title => "Delete album"), album_path(album), :confirm=> 'Are you sure?', :method=> :delete ) if (album.user_id == current_user.id) or is_admin?%> &nbsp; <%if !album.likes.map(&:user_id).include?(current_user.id) %><%= link_to("Like", {:controller => "likes", :action => "all_album_like", :id => album.id}, :remote=>true)%><%else%><%= link_to("Unlike", {:controller => "likes", :action => "all_album_unlike", :id => album.id}, :remote=>true)%><%end%>
          </div>
          <div style="margin-top:8px;margin-left:7px;"><%=album.likes_count.to_s+" people liked" unless album.likes.blank?%> </div>
        </div>
</td>
</tr>
</table>
      </td>
      <% count+=1 %>
      <% if count%3==0%>
        </tr>
      <% end %>
  <% end %>
  </table>
  <%= will_paginate @albums %>
</div>
</center>

app/views/albums/index.html.erb
<html>
<center> 
<div class="row">
 <div class="clear"></div>
    <%= render :partial =>'home/marquee',:locals=>{:message =>"#{current_user.name.titleize}'s Album"} %> 
    <% count=0 %>
    <%flag=0%>
    <table align="center">
      <% @albums.each do |album| %>
        <% if count%3==0 %>
           <tr>
        <% end %>
        <td align="center">
	        <table>
	          <tr>
	            <td>	
                <div class="col1">
                  <div class="album_info">
                    <font color="blue">Album Name : <%= album.album_name.titleize %></font>
                  </div>
                    <% if album.cover_photo %>
                      <%= link_to image_tag( album.cover_photo.image.url(:original) , :height => "200" , :width => "200" , :title => "Show photos") , album_photos_path(album)  %>
	                   <% else %>
	                     <%= link_to image_tag( '/images/admin.jpeg' , :height => "200" , :width => "200" , :title => "Show photos") , album_photos_path(album)  %>
                     <% end %>
                     <div class="album_link">
                       <%= link_to image_tag("/images/show_img.jpeg" ,:height => "20" , :width => "20" , :title => "show album" ), album %>
                       <%= link_to image_tag("/images/edit_img.jpeg" ,:height => "20" , :width => "20" , :title => "Edit album"), edit_album_path(album) %>
                       <%= link_to image_tag("/images/add_img.jpeg" ,:height => "20" , :width => "20" , :title => "Add photo"), new_album_photo_path(album)%>
                       <%= link_to image_tag("/images/delete_img.jpeg" ,:height => "20" , :width => "20" , :title => "Delete album"), delete_album_path(album), :confirm=> 'Are you sure?' %>
                      <%if album.likes.blank?%><%= link_to("Like", {:controller => "likes", :action => "album_like", :id => album.id}, :remote=>true)%><%else%><%= link_to("Unlike", {:controller => "likes", :action => "album_unlike", :id => album.id}, :remote=>true)%><%end%>
                      </div> 
                    </div>
                  </td>
            </tr>
            <tr>
	            <td align="left" class="album_like"> <%=album.likes_count.to_s+" People liked" unless album.likes.blank?%> </td>
	
            </tr>
            </table>
    </td>
          <% count+=1 %>
          <% if count%3==0%>
            </tr>
     <% end %>
  <% end %>
  </table> 
</div>
<%= will_paginate @albums %>
</center>

app/views/albums/new.html.erb
<div class="clear"></div>
<%= render :partial =>'home/marquee',:locals=>{:message =>'New Album'} %>
<%= render 'form' %>

app/views/albums/show.html.erb
<% content_for :header do %>
  <style type="text/css">
    .center_align, th	{
      text-align:center;
    }
  </style>
<% end %>
<div id="album_info">
<div class="clear"></div>
<center>
 <table>
  <tr>    
    <th>Album Name</th>
    <th>Album Description</th>
    <th>User Name</th>   
  </tr>

  <tr>
     <td><b><%= @album.album_name.titleize %></b></td>
     <td><%= @album.album_description.titleize %></td>
     <td><% "#{@album.user_id} #{@album.user.last_name.titleize}" %> </td>
  </tr>  
 </table>
<script>$("tr:odd").css("background-color", "#EBECE4");</script>
</center>
</div>
<div id="edit_back_link">
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', my_albums_albums_path %>
</div>