config/routes.rb
EdAlbum::Application.routes.draw do
match 'exit' => 'home#logout', :as => :logout
match 'delete_album/:id' => 'albums#destroy', :as => :delete_album
match '/albums/:album_id/photos/:photo_id/comments' => 'comments#create', :as => :new_comment
match '/albums/:album_id/delete_photos/:id' => 'photos#destroy', :as => :delete_photo
match '/delete_users/:id' => 'users#destroy', :as=> :delete_user
  resources :albums do
    resources :photos do
      resources :comments
    collection do
      get 'all_album_photos'
    end
    member do
      get  'download'
      get 'set_cover_photo'
    end
    end
   collection do
     get 'my_albums'
     get 'add_photo'
     get 'all_albums'
   end
  end
	
	resources :likes do
	collection do
  get 'photo_like'
	get 'photo_unlike'	
  end
	member do
	get 'album_like'
	get 'album_unlike'
  get 'all_album_like'
	get 'all_album_unlike'
	get 'comment_like'
	get 'comment_unlike'
  get 'solution_like'
  get 'solution_unlike'
	end
	end
  resources :users do
    collection do
     post 'modify_password'
     get 'admin'
     get 'employee'
     get 'change_password'
   end
  end

  resources :home do
    collection do 
      post 'check_login'
      delete 'logout'
      get 'login'
      get 'home_page'
    end
  end

  resources :emailer do
    collection do
     get 'mail'
     get 'new_email' 
     post 'sendmail'
     get 'admin'
     post 'employee_email'
   end
  end
 

  resources :problems do
     get 'new'
  end

	resources :solutions do
     collection do
     	get 'search_solutions'
     	get 'create_solution'
     	post 'solutions' 
     	get 'search'
     end
     member do
     get 'verify'
     get 'reject'
     end
  end
	
	resources :suggestions do
		collection do
    	 get 'event'
    	 get 'create_event'
     end
  end
  


  root :to => 'home#home_page'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/photo.rb
class Photo < ActiveRecord::Base  
  after_create :set_cover_photo
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>",:profile => "150x150>" }, :default_url => '/images/album_cover_d.jpeg'
  belongs_to :album
  has_many :comments
  has_many :users, :through => :comments
  has_many :likes, :as => :likedto

  def set_cover_photo
    unless self.album.cover_photo
      self.album.cover_photo = self
      self.album.save
    end
  end

  def is_owner?(user)
    album =  user.albums.find(:first,:conditions=>[" id = ? " , self.album.id]) 
    album ? true : false 
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :require_user
  layout :set_layout
  # GET /photos
  # GET /photos.json
#   layout 'employee_layout'
  def index
    @album = Album.find(params[:album_id])
    @photos = @album.photos.all.paginate(:page=>params[:page],:per_page=>15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json=> @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @comments = @photo.comments
    @user = User.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json=> @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @album = Album.find(params[:album_id])
    @photo = @album.photos.build()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json=> @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    @album = @photo.album
  end

  # POST /photos
  # POST /photos.json
  def create
    @album = Album.find(params[:album_id])
    params[:photo][:image].each do | image | 
      @photo = @album.photos.build(:image => image)
      @photo.save
    end
    respond_to do |format|
      if @photo.save
        format.html { redirect_to album_photo_path(@album,@photo), notice=> 'Photo was successfully uploaded.' }
        format.json { render json=> @photo, status=> :created, location=> @photo }
      else
        format.html { render :action=> "new" }
        format.json { render :json=> @photo.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @album = Album.find(params[:album_id])
    @photo = @album.photos.build(params[:photo])
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice=> 'Photo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action=> "edit" }
        format.json { render json=> @photo.errors, status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @album = @photo.album
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to album_photos_url }
      format.json { head :ok }
    end
  end

  def download
    @photo = Photo.find(params[:id])
    send_file @photo.image.path, :type => @photo.image.content_type, :disposition => 'attachment' 
  end

  def all_album_photos
    @album = Album.find(params[:album_id])
    @photos = @album.photos
    render :template => 'photos/index'
  end

  def set_cover_photo
    @photo = Photo.find(params[:id])
    @album = @photo.album
    @album.cover_photo_id = @photo.id
    @album.save
    redirect_to my_albums_albums_path
 end
end

app/views/photos/_form.html.erb
<%= form_for :photo, :url => album_photos_path(@album,@photo),:html => { :multipart => true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center><h2>UPLOAD PHOTO IN <%= ((@photo.album).album_name).upcase %> ALBUM</h2></center>
  <br><br>
  <%= f.hidden_field :album_id %>
<div id="moreUploads">
   <input type="file" name="photo[image][]" id="attachment" onchange="document.getElementById('moreUploadsLink').style.display = 'block';" /><br/>
   </div><br><br>
   <div id="moreUploadsLink" style="display:none;">
   <a id="add_new_file" href='#'>Attach another File</a></div>
  

  <div class="actions"><br><br>
  <%= f.submit :UPLOAD %>
  </div>
<% end %>

<script type="text/javascript">
$('document').ready(function() {

  $('#add_new_file').click(function() {
    $('#moreUploads').append('<input id="attachment" type="file" onchange="f1();" name="photo[image][]"/><br/>');
  }); 

  function f1(){
    document.getElementById('moreUploadsLink').style.display = 'block';
  }

});
</script>

app/views/photos/all_album_photos.html.erb
<center>  
<div class="row">
    <%count=0%>
<table border=1>
 <% @photos.each do |photo| %>   
<%if count%3==0%>
<tr>
<%end%>
<td>
    <div class="col1">
       <%= image_tag photo.image.url(:medium), :height => "200" , :width => "200" %>
    </div>
      <div class="link">
         <%= link_to image_tag("/images/download_img.gif" ,:height => "20" , :width => "20" , :title => "Download photo"), download_album_photo_path(photo.album,photo) %>
         <%= link_to image_tag("/images/show_img.jpeg" ,:height => "20" , :width => "20" , :title => "Show photo"), album_photo_path(photo.album,photo) %>
         <%= ( link_to image_tag("/images/delete_img.jpeg" ,:height => "20" , :width => "20" , :title => "Delete photo"), album_photo_path(photo.album,photo), confirm: 'Are you sure?', method: :delete ) if photo.is_owner?(current_user)%>
      </div> 
</td>
<%count+=1%>
<if count%3==0%>
</tr>
<%end%>
 <% end %>
</table>
<%=will_paginate @photos %>
</div>
</center>

app/views/photos/index.html.erb
<center>  
<div class="row">
  <% if @photos.first %>
     <%= render :partial =>'home/marquee',:locals=>{:message => "Photo from "+@photos.first.album.album_name.titleize+"  album"} %>
  <% else %>
    <%= render :partial =>'home/marquee',:locals=>{:message => "Album is empty"} %>
  <% end %>
<table>
<%count=0%>
     <% @photos.each do |photo| %>
<%if count%3==0%>
<tr>
<%end%>

<td>
<table>
<tr>
<td align="center">
    <div class="col1">
       <%= link_to image_tag(photo.image.url(:original), :height => "200" , :width => "200") , album_photo_path(photo.album,photo) %>
       <div class="cover">
          <%= ( link_to "Set as cover photo", set_cover_photo_album_photo_path(photo.album,photo), :confirm=> 'Are you sure?') if photo.is_owner?(current_user) %>
       </div><br>
       <div class="link">
          <%= link_to image_tag("/images/download_img.gif" ,:height => "20" , :width => "20" , :title => "Download photo"), download_album_photo_path(photo.album,photo) %>
          <%= ( link_to image_tag("/images/delete_img.jpeg" ,:height => "20" , :width => "20" , :title => "Delete photo"), delete_photo_path(photo.album,photo), :confirm=> 'Are you sure?',:style=>"margin:7px;" ) if photo.is_owner?(current_user) or is_admin? %>
 <%if !photo.likes.map(&:user_id).include?(current_user.id) %><%= link_to("Like", {:controller => "likes", :action => "photo_like", :id => photo.id}, :remote=>true)%><%else%><%= link_to("Unlike", {:controller => "likes", :action => "photo_unlike", :id => photo.id}, :remote=>true)%><%end%>
       </div> 
     </div>
<div style="margin-top:7px;color:blue;"><%=photo.likes_count.to_s+" People liked" unless photo.likes.blank?%> </div>
</td>
</tr>
<tr>
<td>

</td>
</tr>
</table>
<%count+=1%>
<%if count%3==0%>
</tr>
<%end%>
  <% end %>
</table>
<%=will_paginate @photos %>
</div>
</center>

app/views/photos/show.html.erb
<%= render :partial =>'home/marquee',:locals=>{:message => @photo.image_file_name+" "+(@photo.album).album_name} %>


  <div class="show_photo">
     <a href='<%=@photo.image.url(:original)%>'> <%=image_tag @photo.image.url(:medium) %></a>
  </div>

<hr/>
  <div>
    <% @comments.each do |comment| %>
      <div class="image_commet">
        <div class="comment_user_image"><%= image_tag comment.user.user_image.url(:comment_pic) %></div>
        <div class="comment_contener">
          <div class="comment"><span class="cmt_user_name"><%=comment.user.name.titleize%></span> <%= comment.comment_name %></div>
          <div class=comment_like"><%=comment.created_at.to_s[0,19]%>&nbsp;&nbsp;&nbsp;&nbsp;<%if !comment.likes.map(&:user_id).include?(current_user.id) %><%= link_to("Like", {:controller => "likes", :action => "comment_like", :id => comment.id}, :remote=>true)%><%else%><%= link_to("Unlike", {:controller => "likes", :action => "comment_unlike", :id => comment.id}, :remote=>true)%><%end%></td><td>&nbsp;&nbsp;&nbsp;<span class="cmt_user_name"><%=comment.likes_count.to_s+" people liked" unless comment.likes.blank?%></span> 
          </div>
        </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    <%end%>
  </div>
<div class="clear"></div>
    <div id="show">
       <TEXTAREA id="photo_comment_text" name="comment_name" rows="2" cols="50"></TEXTAREA>
       <input type="button" name="comment" value="comment" id="comment_photo">
    </div>
<%= link_to 'Back', album_photos_path %>

<script type="text/javascript">

$('#comment_photo').click(function(){
var comment_message = $('#photo_comment_text').val();
  if(comment_message!=""){ 
    $.ajax({
      method: 'post',
      data: {comment_name : comment_message},
      url: '/albums/<%=@photo.album.id%>/photos/<%=@photo.id%>/comments',
      success: function(data) {
        window.location.reload();
        $('#photo_comment_text').val("");
      }
    });
  }else{
    alert("Please give comment message !")
  }
});

</script>