config/routes.rb
EdAlbum::Application.routes.draw do
match 'exit' => 'home#logout', :as => :logout
match 'delete_album/:id' => 'albums#destroy', :as => :delete_album
match '/albums/:album_id/photos/:photo_id/comments' => 'comments#create', :as => :new_comment
match '/albums/:album_id/delete_photos/:id' => 'photos#destroy', :as => :delete_photo
match '/delete_users/:id' => 'users#destroy', :as=> :delete_user
  resources :albums do
    resources :photos do
      resources :comments
    collection do
      get 'all_album_photos'
    end
    member do
      get  'download'
      get 'set_cover_photo'
    end
    end
   collection do
     get 'my_albums'
     get 'add_photo'
     get 'all_albums'
   end
  end
	
	resources :likes do
	collection do
  get 'photo_like'
	get 'photo_unlike'	
  end
	member do
	get 'album_like'
	get 'album_unlike'
  get 'all_album_like'
	get 'all_album_unlike'
	get 'comment_like'
	get 'comment_unlike'
  get 'solution_like'
  get 'solution_unlike'
	end
	end
  resources :users do
    collection do
     post 'modify_password'
     get 'admin'
     get 'employee'
     get 'change_password'
   end
  end

  resources :home do
    collection do 
      post 'check_login'
      delete 'logout'
      get 'login'
      get 'home_page'
    end
  end

  resources :emailer do
    collection do
     get 'mail'
     get 'new_email' 
     post 'sendmail'
     get 'admin'
     post 'employee_email'
   end
  end
 

  resources :problems do
     get 'new'
  end

	resources :solutions do
     collection do
     	get 'search_solutions'
     	get 'create_solution'
     	post 'solutions' 
     	get 'search'
     end
     member do
     get 'verify'
     get 'reject'
     end
  end
	
	resources :suggestions do
		collection do
    	 get 'event'
    	 get 'create_event'
     end
  end
  


  root :to => 'home#home_page'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_default_js_css.html.erb
<%= javascript_include_tag "js/jquery.js" %>
<%= javascript_include_tag "js/easySlider1.5.js" %>

<%= javascript_include_tag "js/slider.js" %>
<%= javascript_include_tag "js/superfish.js" %>
<%= javascript_include_tag "js/custom.js" %>

<%= stylesheet_link_tag "styles" %>      
<%= csrf_meta_tag %>

app/views/layouts/_footer.html.erb
<div id="footer">
        <div class="footer-content">    
                <span class="sitename">Intra-Connect</span>
                 <p class="footer-links">
                    <a href=<%= User.home_url(current_user) %>>Home</a>
    				<a href="#container" class="backtotop">Back to top</a>
               	 </p>
                 <div class="clear"></div>
        </div>
        <div class="footer-bottom">
            <p> Copyright &copy; Intra-Connect Team, Privacy Policy and Disclaimer  | <a href="www.systematixtechnocrates.com/">Syatango (formerly Systematix Technocrates) </a></p>
         </div>    
</div>

app/views/layouts/_header.html.erb
<div id="header">
 	<h1><a href=<%= User.home_url(current_user) %>>Intra- <strong>Connect</strong></a></h1>
  <h2>Intra-Connect</h2>
  <div class="clear"></div>
</div>

app/views/layouts/_nav.html.erb
<div id="nav">
  <ul class="sf-menu dropdown">

    <li class="selected"><%= link_to 'Login' ,login_home_index_path%></li>
    <li><a class="has_submenu" href="#">Notification</a>
      <ul>
        <li><%= link_to 'Send Mail',new_email_emailer_index_path  %></li>
      </ul>
    </li>

  <li><a class="has_submenu" href="#">Albums</a>
      <ul>
        <li><%= link_to 'Add New Album', new_album_path %> </li>
        <li><%= link_to 'My Albums' ,my_albums_albums_path%></li>
        <li><%= link_to 'All Albums' ,all_albums_albums_path%></li>
      </ul>
    </li>
    <li><a class="has_submenu" href="#">Post</a>
      <ul>
        <li><%= link_to 'New Post',new_problem_path %></li>
				<li><%= link_to 'Search Solutions',search_solutions_solutions_path %></li>
      </ul>
    </li>
    
    <li><a class="has_submenu" href="#">Employee</a>
      <ul>
        <li><%= link_to 'Add Employee' ,new_user_path%></li>
        <li><%= link_to 'Show Employee Lists' ,users_path%></li>
      </ul>
    </li>
    <li class="selected"><a href=<%= User.home_url(current_user) %>>Home</a></li>
  </ul>


</div>

app/views/layouts/_nav_admin.html.erb
<div id="nav">
  <ul class="sf-menu dropdown">

    <%= render :partial => 'layouts/nav_user' %>
    <li><a class="has_submenu" href="#">Notification</a>
      <ul>
        <li><%= link_to 'Send Mail',new_email_emailer_index_path  %></li>
      </ul>
    </li>

  <li><a class="has_submenu" href="#">Albums</a>
      <ul>
        <li><%= link_to 'Add New Album', new_album_path %> </li>
        <li><%= link_to 'My Albums' ,my_albums_albums_path%></li>
        <li><%= link_to 'All Albums' ,all_albums_albums_path%></li>
      </ul>
    </li>
    <li><a class="has_submenu" href="#">Post</a>
      <ul>
        <li><%= link_to 'New Post',new_problem_path %></li>
				<li><%= link_to 'Search Solutions',search_solutions_solutions_path %></li>
      </ul>
    </li>
    
    <li><a class="has_submenu" href="#">Employee</a>
      <ul>
        <li><%= link_to 'Add Employee' ,new_user_path%></li>
        <li><%= link_to 'Show Employee Lists' ,users_path%></li>
      </ul>
    </li>
    <li class="selected"><a href=<%= User.home_url(current_user) %>>Home</a></li>
  </ul>
</div>

app/views/layouts/_nav_employee.html.erb
<div id="nav">
  <ul class="sf-menu dropdown">
    <%= render :partial => 'layouts/nav_user' %>
    <li><a class="has_submenu" href="#">Notification</a>
      <ul>
        <li><%= link_to 'Send Mail',new_email_emailer_index_path  %></li>
      </ul>
    </li>


    <li><a class="has_submenu" href="#">Albums</a>
      <ul>
        <li><%= link_to 'Add New Album', new_album_path %> </li>
        <li><%= link_to 'My Albums' ,my_albums_albums_path%></li>
        <li><%= link_to 'All Albums' ,all_albums_albums_path%></li>
	
      </ul>
    </li>
    
     <li><a class="has_submenu" href="#">Post</a>
      <ul>
        <li><%= link_to 'New Post',new_problem_path %></li>
				<li><%= link_to 'Search Solutions',search_solutions_solutions_path %></li>
      </ul>
    </li>
    
    <li><a class="has_submenu" href="#">Employee</a>
      <ul>
        <li><%= link_to 'Show Employee Lists' ,users_path%></li>
      </ul>
    </li>
    <li class="selected"><a href=<%= User.home_url(current_user) %>>Home</a></li>
  </ul>
</div>

app/views/layouts/_nav_user.html.erb
<li><a class="has_submenu" href="#"><%= current_user.name.titleize %></a>
      <ul>
        <li><%= link_to 'Change Password' ,change_password_users_path%></li>
        <li ><%= link_to 'Logout' ,logout_path%></li>
      </ul>
</li>

app/views/layouts/_slides_container.html.erb
<div id="slides-container">
        <div id="slides">
            <div>
                <div class="slide-image"><img src="/images/images/image-1	.jpg" alt="Slide #1 image" /></div>
                <div class="slide-text">
                    <h2></h2>
                    <p>
.</p>

            
                </div>
            </div>
            
            <div>
            	<h2>Intra-Connect(Systango!)</h2>
                <p>Systango (formerly Systematix Technocrates) headquartered at Indore, India; is a leading IT software development company that delivers affordable solutions through software development.

Our sole aim and motivation starts with the notion of developing and innovating World's Best Class Software. We believe in leadership through quality service. Nurturing care for clients and partners, knowledge sharing and team work forms the base of our existence. Have a look on niche Systango (formerly Systematix Technocrates) has carved for itself and feel the diligence we deploy.

Our mission is to establish the fact that a team irrespective of its size can lead the crowd by doing quality technology work, can contribute to the opportunity pool for community of the towns which are comparatively unknown on India’s map and in long term become technology partners rather than providers.</p>

            </div>
            
            <div>
                <div class="slide-image slide-image-right"><img src="/images/images/image-4.jpg" alt="Slide #3 image" /></div>
                <div class="slide-text">
                    <h2></h2>
                    <p></p>

            
                </div>
            </div>
		</div>
        <div class="controls"><span class="jFlowNext"><span>Next</span></span><span class="jFlowPrev"><span>Prev</span></span></div>        
        <div id="myController" class="hidden"><span class="jFlowControl">Slide 1</span><span class="jFlowControl">Slide 1</span><span class="jFlowControl">Slide 1</span></div>
    </div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ED ALBUM</title>
      <%= yield :header %>
     <%= render :partial => 'layouts/default_js_css' %>
   </head>
   <body>
     <div id="container">
       <%= render :partial => 'layouts/header' %>
       <%= render :partial => nav %>       
       <%= render :partial => 'layouts/slides_container' %>  
        <div id="body" class="has-slider">
     <% unless flash[:notice].blank? %>
      <div class="clear"> </div>
      <table id='notice_msg' border="1" ><tr><td> <%= flash[:notice] %></td></tr></table>
     <% end %>
      <% unless flash[:error].blank? %>
      <div class="clear"> </div>
        <table id='error_msg' border="1" ><tr><td> <%= flash[:error] %></td></tr></table>

      <%end%>
       <div class="middile">
            <%= yield %>
       </div>     
    	<div class="clear"></div>
    </div>
   <%= render :partial => 'layouts/footer' %>    
   </body>
 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intra-Connect</title>
      <%= yield :header %>
     <%= render :partial => 'layouts/default_js_css' %>
   </head>
   <body>
     <div id="container">
       <%= render :partial => 'layouts/header' %>
       <%= render :partial => nav %>
       <%= render :partial => 'layouts/slides_container' %>              
       <div id="body" class="has-slider">   
        <% unless flash[:notice].blank? %>
      <div class="clear"> </div>
      <table id='notice_msg' border="1" ><tr><td> <%= flash[:notice] %></td></tr></table>
     <% end %>
      <% unless flash[:error].blank? %>

       <div class="clear"> </div>
        <table id='error_msg' border="1" ><tr><td> <%= flash[:error] %></td></tr></table>

      <%end%>
          <div class="middile">
            <%= yield %>
          </div>     
    	    <div class="clear"></div>
       </div>

      <%= render :partial => 'layouts/footer' %>    
   </body>
 </html>

app/views/layouts/employee_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ED ALBUM</title>
      <%= yield :header %>
      <%= render :partial => 'layouts/default_js_css' %>
   </head>
   <body>
     <div id="container">
       <%= render :partial => 'layouts/header' %>
       <%= render :partial => nav %>       
       <%= render :partial => 'layouts/slides_container' %>  
        <div id="body" class="has-slider">
     <% unless flash[:notice].blank? %>
      <div class="clear"> </div>
      <table id='notice_msg' border="1" ><tr><td> <%= flash[:notice] %></td></tr></table>
     <% end %>
      <% unless flash[:error].blank? %>
        <div class="clear"> </div>
        <table id='error_msg' border="1" ><tr><td> <%= flash[:error] %></td></tr></table>
      <%end%>
       <div class="middile">
            <%= yield %>
       </div>     
    	<div class="clear"></div>
    </div>
   <%= render :partial => 'layouts/footer' %>    
   </body>
 </html>